name: Appium CI Github Actions
# on push we will trigger our code
on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

  execution-test:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Run Appium Tests
        run: ./gradlew test -Dproperties="appiumexecute/android.conf" -Dcucumber.filter.tags="@testExitoso" aggregate --info # running our test with info to check the results


  upload-report-serenity:
    needs: execution-test
    runs-on: self-hosted

    steps:
      - name: Upload Serenity Report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: serenity-report
          path: target/site/serenity


  deploy-report-serenity:
    needs: upload-report-serenity
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: serenity-report
          path: ./target/site/serenity

      - name: Deploy to GitHub Pages serenity report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/serenity
      - name: Output GitHub Pages URL
        run: echo "GitHub Pages URL:" + " https://carloslopera89.github.io/appium-demo-android-ios/"